import type { ColumnType, Selectable } from 'kysely';

/* ------------------------------------------------------------------ *
 * Kysely table interfaces.
 *
 * These mirror the DATABASE, not the domain model. SQLite has no boolean
 * and no date type: `enabled`/`udp` are INTEGER 0/1 and `created_at` is a
 * DATETIME stored as text. Declaring them honestly here is what forces the
 * row -> domain coercion to happen in db.ts instead of being forgotten.
 * ------------------------------------------------------------------ */

export interface SubscriptionsTable {
  id: string;
  name: string;
  url: string;
  /** SQLite INTEGER 0/1, column DEFAULT 1. Coerced to boolean in toSubscription(). */
  enabled: number;
  /**
   * ColumnType<Select, Insert, Update>.
   *
   * `update: never` is load-bearing, not decoration: it makes mentioning
   * created_at inside .doUpdateSet() a COMPILE error, so an upsert cannot
   * clobber the original creation time. `Generated<string>` is the common
   * shorthand but expands to ColumnType<string, string|undefined, string>,
   * which would happily let you overwrite it.
   */
  created_at: ColumnType<string, string | undefined, never>;
}

export interface ProfilesTable {
  key: string;
  target: string;
  /** JSON array string, e.g. '["sub_01","sub_02"]'. Parsed defensively by toProfile(). */
  source_ids: string;
  custom_ruleset: string | null;
  exclude_remarks: string | null;
  /** SQLite INTEGER 0/1, column DEFAULT 1. Coerced to boolean in toProfile(). */
  udp: number;
  created_at: ColumnType<string, string | undefined, never>;
}

export interface Database {
  subscriptions: SubscriptionsTable;
  profiles: ProfilesTable;
}

export type SubscriptionRow = Selectable<SubscriptionsTable>;
export type ProfileRow = Selectable<ProfilesTable>;

/* ------------------------------------------------------------------ *
 * Domain types - what the rest of the app sees.
 * Booleans are real booleans, source_ids is a real string[].
 * ------------------------------------------------------------------ */

export interface Subscription {
  id: string;
  name: string;
  url: string;
  enabled: boolean;
  createdAt: string;
}

export interface Profile {
  key: string;
  target: string;
  sourceIds: string[];
  /**
   * false when the stored source_ids was not a JSON array of strings. The
   * request path uses this to fail loudly instead of silently serving an
   * empty config built from zero sources.
   */
  sourceIdsValid: boolean;
  customRuleset: string | null;
  excludeRemarks: string | null;
  udp: boolean;
  createdAt: string;
}

/* ---- write inputs ---- */

export interface UpsertSubscriptionInput {
  /** Omitted -> generated by newSubscriptionId(). */
  id?: string;
  name: string;
  url: string;
  /** Defaults to true. */
  enabled?: boolean;
}

export interface UpsertProfileInput {
  key: string;
  /** Defaults to 'clash'. */
  target?: string;
  /** Required; already validated and de-duplicated by the route. */
  sourceIds: string[];
  /** Defaults to null. */
  customRuleset?: string | null;
  /** Defaults to null. */
  excludeRemarks?: string | null;
  /** Defaults to true. */
  udp?: boolean;
}

/* ---- shared API error shape ---- */

export interface ApiErrorBody {
  error: {
    code: string;
    message: string;
    details?: unknown;
  };
}
